#!/usr/bin/env python3
"""Build an Excel QC report from corrected overall and split QC reports.

Inputs are the QC report directories generated by:
- report_qc_probe_loss_overall_fixed.py
- report_qc_probe_loss_by_split.py

The workbook intentionally separates:
1. array design / pre-QC coverage,
2. sample-level QC affected/lost CpGs,
3. literature/reference array coverage values.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from openpyxl.utils import get_column_letter


CLOCK_ORDER = ["Horvath", "Hannum", "PhenoAge", "GrimAgeV1", "GrimAgeV2", "DunedinPACE"]
DATASET_ORDER = ["EPICv2", "EPICv2 training", "EPICv2 validation", "MSA", "MSA training", "MSA validation"]

# Literature/reference coverage from the table sent by collaborator.
# These are array-design-style numbers, not sample-level QC numbers.
LITERATURE_COVERAGE = {
    ("EPICv2", "Horvath"): (353, 340),
    ("EPICv2", "Hannum"): (71, 64),
    ("EPICv2", "PhenoAge"): (513, 495),
    ("EPICv2", "GrimAgeV1"): (1030, 834),
    ("EPICv2", "GrimAgeV2"): (1030, 834),
    ("EPICv2", "DunedinPACE"): (173, 142),
    ("MSA", "Horvath"): (353, 346),
    ("MSA", "Hannum"): (71, 68),
    ("MSA", "PhenoAge"): (513, 508),
    ("MSA", "GrimAgeV1"): (1030, 980),
    ("MSA", "GrimAgeV2"): (1030, 980),
    ("MSA", "DunedinPACE"): (173, 169),
}

DUNEDINPACE_TOTAL_REQUIRED = {
    "EPICv2": (20000, 17198),
    "MSA": (20000, 9506),
}


def read_overall(report_dir: Path, dataset_label: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    clock_path = report_dir / "clock_qc_overlap_summary.csv"
    summary_path = report_dir / "qc_probe_loss_summary.csv"
    if not clock_path.is_file():
        raise FileNotFoundError(clock_path)
    if not summary_path.is_file():
        raise FileNotFoundError(summary_path)
    clock = pd.read_csv(clock_path)
    clock["dataset_group"] = dataset_label
    summary = pd.read_csv(summary_path).rename(columns={"value": dataset_label})
    return clock, summary


def read_split(report_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame, Optional[pd.DataFrame]]:
    clock_path = report_dir / "split_clock_qc_overlap_summary.csv"
    summary_path = report_dir / "split_qc_probe_loss_summary.csv"
    unmatched_path = report_dir / "split_unmatched_samples.csv"
    if not clock_path.is_file():
        raise FileNotFoundError(clock_path)
    if not summary_path.is_file():
        raise FileNotFoundError(summary_path)
    clock = pd.read_csv(clock_path)
    clock["dataset_group"] = (
        clock["dataset"].astype(str) + " " + clock["split"].replace({"testing": "validation"}).astype(str)
    )
    summary = pd.read_csv(summary_path)
    summary["dataset_group"] = (
        summary["dataset"].astype(str) + " " + summary["split"].replace({"testing": "validation"}).astype(str)
    )
    unmatched = pd.read_csv(unmatched_path) if unmatched_path.is_file() else None
    return clock, summary, unmatched


def add_literature_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    lit_required = []
    lit_present = []
    lit_missing = []
    lit_delta_present = []
    lit_note = []
    for _, row in df.iterrows():
        dataset = str(row["dataset"])
        base = "EPICv2" if dataset.startswith("EPICv2") else "MSA" if dataset.startswith("MSA") else dataset
        clock = str(row["clock"])
        key = (base, clock)
        if key in LITERATURE_COVERAGE:
            req, present = LITERATURE_COVERAGE[key]
            lit_required.append(req)
            lit_present.append(present)
            lit_missing.append(req - present)
            lit_delta_present.append(int(row["present_before_qc_n"]) - present)
            lit_note.append("reference_array_design_core_clock")
        else:
            lit_required.append(pd.NA)
            lit_present.append(pd.NA)
            lit_missing.append(pd.NA)
            lit_delta_present.append(pd.NA)
            lit_note.append("")
    df["reference_required_cpg_n"] = lit_required
    df["reference_array_present_n"] = lit_present
    df["reference_array_missing_n"] = lit_missing
    df["delta_present_before_qc_vs_reference"] = lit_delta_present
    df["reference_note"] = lit_note
    return df


def make_clock_summary(overall_clocks: list[pd.DataFrame], split_clocks: list[pd.DataFrame]) -> pd.DataFrame:
    df = pd.concat(overall_clocks + split_clocks, ignore_index=True, sort=False)
    if "dataset_group" not in df.columns:
        df["dataset_group"] = df["dataset"]
    # Corrected derived fields: always recompute these to avoid spreadsheet carry-over mistakes.
    df["missing_before_qc_n_recalculated"] = df["required_cpg_n"] - df["present_before_qc_n"]
    if "present_after_qc_n" in df.columns:
        df["missing_after_qc_n_recalculated"] = df["required_cpg_n"] - df["present_after_qc_n"]
    df = add_literature_columns(df)
    df["dataset_group"] = pd.Categorical(df["dataset_group"], DATASET_ORDER, ordered=True)
    df["clock"] = pd.Categorical(df["clock"], CLOCK_ORDER, ordered=True)
    return df.sort_values(["dataset_group", "clock"]).reset_index(drop=True)


def make_array_design_reference_sheet() -> pd.DataFrame:
    rows = []
    for (array, clock), (required, present) in LITERATURE_COVERAGE.items():
        rows.append({
            "array": array,
            "clock": clock,
            "required_cpg_n": required,
            "reference_array_present_n": present,
            "reference_array_missing_n": required - present,
            "reference_array_present_pct": 100.0 * present / required,
            "note": "Values transcribed from collaborator-provided reference table; use only for array-design coverage comparison, not QC loss.",
        })
    for array, (required, present) in DUNEDINPACE_TOTAL_REQUIRED.items():
        rows.append({
            "array": array,
            "clock": "DunedinPACE total required probes",
            "required_cpg_n": required,
            "reference_array_present_n": present,
            "reference_array_missing_n": required - present,
            "reference_array_present_pct": 100.0 * present / required,
            "note": "Not the same as Biolearn DunedinPACE core 173 CpGs.",
        })
    df = pd.DataFrame(rows)
    df["array"] = pd.Categorical(df["array"], ["EPICv2", "MSA"], ordered=True)
    return df.sort_values(["array", "clock"]).reset_index(drop=True)


def pivot_summary(overall_summaries: dict[str, pd.DataFrame], split_summaries: list[pd.DataFrame]) -> pd.DataFrame:
    """Create a wide summary table while preserving mixed value types.

    The summary contains both numeric values and strings such as
    final_beta_orientation = "sample_rows".  Therefore, this function
    avoids initializing a float-only DataFrame and instead builds the
    table from nested dictionaries.
    """
    data = {}
    metric_order = []

    def put(metric, label, value):
        metric = str(metric)
        label = str(label)

        if metric not in data:
            data[metric] = {}
            metric_order.append(metric)

        data[metric][label] = value

    # Overall summaries: qc_probe_loss_summary.csv has columns:
    # metric,value, where "value" has already been renamed to dataset label.
    for label, df in overall_summaries.items():
        if df is None or df.empty:
            continue

        if "metric" not in df.columns or label not in df.columns:
            continue

        for _, row in df.iterrows():
            put(row["metric"], label, row[label])

    # Split summaries: split_qc_probe_loss_summary.csv has one row per split.
    for df in split_summaries:
        if df is None or df.empty:
            continue

        for _, row in df.iterrows():
            label = row.get("dataset_group", None)
            if label is None or pd.isna(label):
                dataset = row.get("dataset", "")
                split = row.get("split", "")
                label = f"{dataset} {split}"

            for k, v in row.items():
                if k in {"dataset", "split", "dataset_group"}:
                    continue
                put(k, label, v)

    rows = []
    for metric in metric_order:
        row = {"metric": metric}
        row.update(data[metric])
        rows.append(row)

    out = pd.DataFrame(rows)

    # Keep columns in a stable, readable order when present.
    preferred_cols = ["metric"] + DATASET_ORDER
    existing_preferred = [c for c in preferred_cols if c in out.columns]
    remaining = [c for c in out.columns if c not in existing_preferred]
    out = out[existing_preferred + remaining]

    return out

def write_excel(path: Path, sheets: dict[str, pd.DataFrame]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for name, df in sheets.items():
            df.to_excel(writer, sheet_name=name[:31], index=False)

    wb = load_workbook(path)
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    header_font = Font(bold=True)
    thin = Side(style="thin", color="B7B7B7")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    for ws in wb.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.border = border
            cell.alignment = Alignment(wrap_text=True)
        for col in ws.columns:
            col_letter = get_column_letter(col[0].column)
            max_len = 0
            for cell in col[:1000]:
                val = "" if cell.value is None else str(cell.value)
                max_len = max(max_len, len(val))
            ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 48)
    wb.save(path)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--epicv2-overall", type=Path, required=True)
    ap.add_argument("--msa-overall", type=Path, required=True)
    ap.add_argument("--epicv2-split", type=Path, required=True)
    ap.add_argument("--msa-split", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=Path("qc_probe_loss_summary.corrected.xlsx"))
    args = ap.parse_args()

    epic_overall_clock, epic_overall_summary = read_overall(args.epicv2_overall, "EPICv2")
    msa_overall_clock, msa_overall_summary = read_overall(args.msa_overall, "MSA")
    epic_split_clock, epic_split_summary, epic_unmatched = read_split(args.epicv2_split)
    msa_split_clock, msa_split_summary, msa_unmatched = read_split(args.msa_split)

    clock_summary = make_clock_summary([epic_overall_clock, msa_overall_clock], [epic_split_clock, msa_split_clock])
    pipeline_summary = pivot_summary(
        {"EPICv2": epic_overall_summary, "MSA": msa_overall_summary},
        [epic_split_summary, msa_split_summary],
    )
    reference = make_array_design_reference_sheet()
    definitions = pd.DataFrame([
        {"term": "present_before_qc_n", "definition": "Number of Biolearn-required CpGs present in the pre-QC collapsed CpG universe calculated from this pipeline."},
        {"term": "missing_before_qc_n_recalculated", "definition": "required_cpg_n - present_before_qc_n. Use this corrected field for missing-before-QC."},
        {"term": "qc_affected_cpg_n", "definition": "Number of required CpGs affected by QC in at least one sample."},
        {"term": "qc_completely_lost_cpg_n", "definition": "Number of required CpGs failing QC in all matched samples for the group."},
        {"term": "reference_array_present_n", "definition": "Array-design coverage from the collaborator-provided/literature reference table. This is not sample-level QC."},
        {"term": "delta_present_before_qc_vs_reference", "definition": "present_before_qc_n - reference_array_present_n. Non-zero values indicate different CpG-list / manifest / collapse definitions."},
    ])

    sheets = {
        "Pipeline_QC_Summary": pipeline_summary,
        "Clock_QC_Coverage": clock_summary,
        "Reference_Array_Coverage": reference,
        "Definitions": definitions,
    }
    if epic_unmatched is not None:
        sheets["EPICv2_Unmatched_Samples"] = epic_unmatched
    if msa_unmatched is not None:
        sheets["MSA_Unmatched_Samples"] = msa_unmatched

    write_excel(args.out, sheets)
    print(f"[Done] wrote {args.out}")


if __name__ == "__main__":
    main()

